### ISSUE TITLE
Output table displays outcomes & opp scores in a random order 

### ISSUE THREAD

**Issue by linzi-create** [jpcarrascal/OppScoreWeb#4]
Everything works great! Just noticed that while the input data listed the outcomes in a certain order, the order in output is random. Every new calculation with the same data set will yield a different order. This might make it challenging to do a comparison between maps, for example, if we wanted to see whether customers segments would impact the opp map distribution.

![Screen Shot 2022-10-21 at 4 56 24 PM](https://user-images.githubusercontent.com/77656968/197306982-f7956602-0abc-4529-b2df-cb642c35d95e.png)

**Comment by jpcarrascal** [comment]
Hi @linzi-create,
The outcome order should be in descending order of OppScore. Isn't it the case for your data? Can you share a screenshot of the whole table? Thanks!

**Comment by jpcarrascal** [comment]
No further comments, closing.
