### ISSUE TITLE
Case problem with survey importer 

### ISSUE THREAD

**Issue by robflaherty** [jpcarrascal/OppScoreWeb#5]
Thanks for this tool! I ran into a bug with the survey importer. My data had `Importance` and `Satisfaction` labels (uppercase), which passes the validator because it `toLowerCase()`s them, but fails here when they aren't lowercased:

```
if(impsats[j] == "importance")
  dp.importance = scores[j];
else
  dp.satisfaction = scores[j];
```

This resulted in only one column of scores coming through.

I [fixed in my fork](https://github.com/robflaherty/OppScoreWeb/commit/451dc9f20f4f8b90a1e8c44ccb4050163e570c93) and was going to submit a PR but figured you wouldn't want the messy commit with the line ending changes :)

**Comment by jpcarrascal** [comment]
Hey @robflaherty , sorry for the super delayed response. Thanks for catching that. It should be fixed now.
Cheers!
JP
